[build]
  command = "npm install --legacy-peer-deps && find node_modules -path '*/ajv-keywords/keywords/_formatLimit.js' -exec sed -i 's/var formats = ajv._formats;/var formats = (ajv._formats || ajv.formats) || {};/' {} + && DISABLE_ESLINT_PLUGIN=true npm run build"
  publish = "build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
